<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends BaseRepository
{
    /**
    * Get all Countries with paginator and Order.
    *
    * @param integer $currentPage The current page (passed from controller)
    * @return \Doctrine\ORM\Tool\Pagination\Paginator
    */
    public function getAllCountries($currentPage = 1, $limit = 5)
    {
        $query = $this->createQueryBuilder('c')
                ->orderBy('c.name', 'ASC')
                ->getQuery();

        $paginator = $this->paginate($query, $currentPage, $limit);

        return $paginator;
    }
}
