<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * EraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EraRepository extends BaseRepository
{
    /**
    * Get all Eras with paginator and Order.
    *
    * @param integer $currentPage The current page (passed from controller)
    * @return \Doctrine\ORM\Tool\Pagination\Paginator
    */
    public function getAllEras($currentPage = 1, $limit = 5)
    {
        $query = $this->createQueryBuilder('e')
                ->orderBy('e.name', 'ASC')
                ->getQuery();

        $paginator = $this->paginate($query, $currentPage, $limit);

        return $paginator;
    }

    /**
    * Get n era.
    *
    * @return n eras
    */
    public function getCountEras()
    {
        $qb = $this->createQueryBuilder('e');
        $qb->select('count(e.id)');
        $count = $qb->getQuery()->getSingleScalarResult();
        return $count;
    }
}
