<?php

namespace AppBundle\Repository;

/**
 * MilestoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MilestoneRepository extends BaseRepository
{

    /**
    * Get all Milestones with paginator and Order.
    *
    * @param integer $currentPage The current page (passed from controller)
    * @return \Doctrine\ORM\Tool\Pagination\Paginator
    */
    public function getAllMilestones($currentPage = 1, $limit = 5)
    {
        $query = $this->createQueryBuilder('m')
                ->orderBy('m.title', 'ASC')
                ->getQuery();

        $paginator = $this->paginate($query, $currentPage, $limit);

        return $paginator;
    }
}
