<?php

namespace AppBundle\Repository;

/**
 * PolityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PolityRepository extends \Doctrine\ORM\EntityRepository
{
}
