<?php
namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PolityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PolityRepository extends BaseRepository
{
    /**
    * Get all Polities with paginator and Order.
    *
    * @param integer $currentPage The current page (passed from controller)
    * @return \Doctrine\ORM\Tool\Pagination\Paginator
    */
    public function getAllPolities($currentPage = 1, $limit = 5)
    {
        $query = $this->createQueryBuilder('p')
                ->orderBy('p.name', 'ASC')
                ->getQuery();

        $paginator = $this->paginate($query, $currentPage, $limit);

        return $paginator;
    }

    /**
    * Get n polity.
    *
    * @return n Polities
    */
    public function getCountPolities()
    {
        $qb = $this->createQueryBuilder('p');
        $qb->select('count(p.id)');
        $count = $qb->getQuery()->getSingleScalarResult();
        return $count;
    }
}
