<?php

namespace AppBundle\Repository;

/**
 * TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRepository extends BaseRepository
{
    /**
    * Get all Type with paginator and Order.
    *
    * @param integer $currentPage The current page (passed from controller)
    * @return \Doctrine\ORM\Tool\Pagination\Paginator
    */
    public function getAllTypes($currentPage = 1, $limit = 5)
    {
        $query = $this->createQueryBuilder('t')
                ->orderBy('t.name', 'ASC')
                ->getQuery();

        $paginator = $this->paginate($query, $currentPage, $limit);

        return $paginator;
    }

    /**
    * Get n Type.
    *
    * @return n Type milestones
    */
    public function getCountTypeMilestones()
    {
        $qb = $this->createQueryBuilder('t');
        $qb->select('count(t.id)');
        $count = $qb->getQuery()->getSingleScalarResult();
        return $count;
    }
}
