<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends BaseRepository
{
  /**
  * Get all Users with paginator and Order.
  *
  * @param integer $currentPage The current page (passed from controller)
  * @return \Doctrine\ORM\Tool\Pagination\Paginator
  */
  public function getAllUsers($currentPage = 1, $limit = 5)
  {
      $query = $this->createQueryBuilder('u')
              ->orderBy('u.username', 'ASC')
              ->getQuery();

      $paginator = $this->paginate($query, $currentPage, $limit);

      return $paginator;
  }
}
